### ISSUE TITLE
Probloma na criacao do qrcode

### ISSUE THREAD

**Issue by rogerbbh** [leonardomdr/gn-pix-api#1]
Opa estou tentando usar sua API porem ele não gera o qrcode analisando as linhas vi que ele para em 

public function generatePix($data, $txid = '') {

como posso solucionar ?
Obg

**Comment by leonardomdr** [comment]
Qual erro está dando? Pegue no log de erros do php ou habilite a
visualização dos erros em seu codigo php. Depois  compartilhe aqui tanto o
erro quanto o código para que eu possa tentar te ajudar.

Em qui, 1 de jul de 2021 03:53, rogerbbh ***@***.***>
escreveu:
